name: "Publish blog contents"

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DEST_DIR: "Attsun1031.github.io"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Checkout blog repo
        uses: actions/checkout@v2
        with:
          repository: "Attsun1031/Attsun1031.github.io"
          ref: ${{ github.head_ref }}
          path: ${{ env.DEST_DIR }}
          token: ${{ secrets.PAT_FOR_SUBMODULE }}

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Build contents
        run: |
          npm install
          npm run export
          ./scripts/copy_to_publish.sh ${{ env.DEST_DIR }}

      - name: Create a pull request
        id: create_pr
        # SEE: https://github.com/peter-evans/create-pull-request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT_FOR_SUBMODULE }}
          base: "main"
          path: ${{ env.DEST_DIR }}
          delete-branch: true
          draft: false
          title: "Publish blog contents"
          commit-message: "Publish blog contents"
          labels: release
          body: |
            Merge and publish blog contents.
            The pull request was automatically created by GitHub Actions.

            **Please do not squash merge, because conflicts will occur.**
